// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxKjz6gL7H6MM9bMxUUgXh3ErEnJjOfvw',
    appId: '1:543683569205:web:6116b71e4abfe4dda4337c',
    messagingSenderId: '543683569205',
    projectId: 'todo-application-b6385',
    authDomain: 'todo-application-b6385.firebaseapp.com',
    storageBucket: 'todo-application-b6385.firebasestorage.app',
    measurementId: 'G-9KW8R2S892',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQJrMaYlzKI4T2x3cEkNr4avBILcSI1w',
    appId: '1:543683569205:android:59ca0811bbde783ba4337c',
    messagingSenderId: '543683569205',
    projectId: 'todo-application-b6385',
    storageBucket: 'todo-application-b6385.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxKjz6gL7H6MM9bMxUUgXh3ErEnJjOfvw',
    appId: '1:543683569205:web:e0b73e7e11d863b2a4337c',
    messagingSenderId: '543683569205',
    projectId: 'todo-application-b6385',
    authDomain: 'todo-application-b6385.firebaseapp.com',
    storageBucket: 'todo-application-b6385.firebasestorage.app',
    measurementId: 'G-0FC45VJG04',
  );
}
